### ISSUE TITLE
Tyk installation path changed after updating docker image to use packages

### ISSUE THREAD

**Issue by buger** [TykTechnologies/tyk-hybrid-docker#12]
Previously it was /opt/tyk now it is /opt/tyk-gateway. It broke custom tyk configs for users who mounted them to /opt/tyk/tyk.conf.

**Comment by excieve** [comment]
We could do something like for compatibility:
https://github.com/TykTechnologies/tyk-hybrid-docker/blob/master/entrypoint.sh#L35
```.bash
CONFPATH=/opt/tyk-gateway
[ -f /opt/tyk/tyk.conf ] && CONFPATH=/opt/tyk
./tyk$TYKLANG --conf=$CONFPATH/tyk.conf
```

**Comment by buger** [comment]
Looks good, waits till next week.
